version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"